# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  # Only show new issues in PRs
  new-from-rev: origin/main

# output section removed for v2 compatibility

# Linter-specific settings
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  gosec:
    severity: medium
    confidence: medium
  gocyclo:
    min-complexity: 30  # Increased from default 10
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - commentedOutCode
      - whyNoLint

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - lll
    - nlreturn
    - wsl
    - dupl
    - revive  # Too many false positives
    - goconst # Too noisy
    - unparam # Many false positives with interfaces


issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  new: true  # Only show new issues in PRs
  # Set a high threshold so we only fail on critical issues
  # This allows gradual improvement of the codebase
  max-issues: 200
  # Exclude some linters from test files
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - dupl
        - goconst
    - path: test_utils\.go
      linters:
        - gosec
        - errcheck
    # Exclude some common false positives
    - linters:
        - gosec
      text: "G304: Potential file inclusion via variable"
      source: "#nosec"
    - linters:
        - gosec
      text: "G404:"
    - linters:
        - revive
      text: "exported:"
    - linters:
        - unused
      text: "is unused"
      source: "//go:build"