# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - lll
    - nlreturn
    - wsl


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false