blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/perplext/nsd/tree/main/docs
    about: Read the official documentation and guides
  - name: 💬 GitHub Discussions
    url: https://github.com/perplext/nsd/discussions
    about: Ask questions and discuss with the community
  - name: 🔧 Troubleshooting Guide
    url: https://github.com/perplext/nsd/blob/main/docs/TROUBLESHOOTING.md
    about: Common issues and solutions
  - name: 🧩 Plugin Development
    url: https://github.com/perplext/nsd/blob/main/docs/PLUGIN_DEVELOPMENT.md
    about: Learn how to develop plugins for NSD